"""create initial operational schema

Revision ID: bf5974834806
Revises:
Create Date: 2026-05-25 14:18:23.736557

"""

# ruff: noqa: E501
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "bf5974834806"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organisations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("nom_entite", sa.String(length=255), nullable=False),
        sa.Column("type_secteur", sa.Enum("PRIVE", "PUBLIC", name="type_secteur"), nullable=False),
        sa.Column("identifiant_legal", sa.String(length=64), nullable=True),
        sa.Column("email_facturation", sa.String(length=320), nullable=True),
        sa.Column("adresse_facturation", sa.String(length=1024), nullable=True),
        sa.Column("numero_tva_intracommunautaire", sa.String(length=32), nullable=True),
        sa.Column("stripe_customer_id", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organisations")),
        sa.UniqueConstraint("stripe_customer_id", name=op.f("uq_organisations_stripe_customer_id")),
    )
    op.create_table(
        "roles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("nom_role", sa.String(length=128), nullable=False),
        sa.Column(
            "permissions",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_roles")),
        sa.UniqueConstraint("nom_role", name=op.f("uq_roles_nom_role")),
    )
    op.create_table(
        "utilisateurs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("nom", sa.String(length=255), nullable=False),
        sa.Column("prenom", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("telephone_mobile", sa.String(length=32), nullable=True),
        sa.Column("mot_de_passe_hash", sa.String(length=255), nullable=False),
        sa.Column("code_pin", sa.String(length=255), nullable=True),
        sa.Column("derniere_connexion", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_utilisateurs")),
    )
    op.create_index(op.f("ix_utilisateurs_email"), "utilisateurs", ["email"], unique=True)
    op.create_table(
        "abonnements",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organisation_id", sa.UUID(), nullable=False),
        sa.Column("stripe_subscription_id", sa.String(length=255), nullable=False),
        sa.Column("stripe_price_id", sa.String(length=255), nullable=False),
        sa.Column(
            "statut",
            sa.Enum(
                "TRIALING",
                "ACTIVE",
                "PAST_DUE",
                "CANCELED",
                "INCOMPLETE",
                "INCOMPLETE_EXPIRED",
                "UNPAID",
                "PAUSED",
                name="statut_abonnement",
            ),
            nullable=False,
        ),
        sa.Column("intervalle", sa.String(length=32), nullable=False),
        sa.Column(
            "features_limits",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("date_debut", sa.DateTime(timezone=True), nullable=False),
        sa.Column("date_fin_periode", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organisation_id"],
            ["organisations.id"],
            name=op.f("fk_abonnements_organisation_id_organisations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_abonnements")),
        sa.UniqueConstraint(
            "stripe_subscription_id", name=op.f("uq_abonnements_stripe_subscription_id")
        ),
    )
    op.create_index(
        op.f("ix_abonnements_organisation_id"), "abonnements", ["organisation_id"], unique=False
    )
    op.create_table(
        "etablissements",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organisation_id", sa.UUID(), nullable=False),
        sa.Column("nom_site", sa.String(length=255), nullable=False),
        sa.Column("adresse", sa.String(length=1024), nullable=True),
        sa.Column("siret", sa.String(length=14), nullable=True),
        sa.Column("type_activite", sa.String(length=128), nullable=True),
        sa.Column("timezone", sa.String(length=64), server_default="Europe/Paris", nullable=False),
        sa.Column("telephone_site", sa.String(length=32), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organisation_id"],
            ["organisations.id"],
            name=op.f("fk_etablissements_organisation_id_organisations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_etablissements")),
        sa.UniqueConstraint("siret", name=op.f("uq_etablissements_siret")),
    )
    op.create_index(
        op.f("ix_etablissements_organisation_id"),
        "etablissements",
        ["organisation_id"],
        unique=False,
    )
    op.create_table(
        "affectations_site",
        sa.Column("utilisateur_id", sa.UUID(), nullable=False),
        sa.Column("etablissement_id", sa.UUID(), nullable=False),
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.Column("poste_principal", sa.String(length=128), nullable=True),
        sa.Column(
            "affecte_le",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["etablissement_id"],
            ["etablissements.id"],
            name=op.f("fk_affectations_site_etablissement_id_etablissements"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
            name=op.f("fk_affectations_site_role_id_roles"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["utilisateur_id"],
            ["utilisateurs.id"],
            name=op.f("fk_affectations_site_utilisateur_id_utilisateurs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "utilisateur_id", "etablissement_id", "role_id", name=op.f("pk_affectations_site")
        ),
    )
    op.create_table(
        "equipements",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("etablissement_id", sa.UUID(), nullable=False),
        sa.Column("nom", sa.String(length=255), nullable=False),
        sa.Column("temperature_min_cible", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("temperature_max_cible", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["etablissement_id"],
            ["etablissements.id"],
            name=op.f("fk_equipements_etablissement_id_etablissements"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_equipements")),
    )
    op.create_index(
        op.f("ix_equipements_etablissement_id"), "equipements", ["etablissement_id"], unique=False
    )
    op.create_table(
        "pointages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("etablissement_id", sa.UUID(), nullable=False),
        sa.Column("utilisateur_id", sa.UUID(), nullable=False),
        sa.Column(
            "type_evenement",
            sa.Enum(
                "CLOCK_IN", "BREAK_START", "BREAK_END", "CLOCK_OUT", name="type_evenement_pointage"
            ),
            nullable=False,
        ),
        sa.Column("pointe_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["etablissement_id"],
            ["etablissements.id"],
            name=op.f("fk_pointages_etablissement_id_etablissements"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["utilisateur_id"],
            ["utilisateurs.id"],
            name=op.f("fk_pointages_utilisateur_id_utilisateurs"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pointages")),
    )
    op.create_index(
        op.f("ix_pointages_etablissement_id"), "pointages", ["etablissement_id"], unique=False
    )
    op.create_index(
        op.f("ix_pointages_utilisateur_id"), "pointages", ["utilisateur_id"], unique=False
    )
    op.create_table(
        "releves_temperature",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("etablissement_id", sa.UUID(), nullable=False),
        sa.Column("equipement_id", sa.UUID(), nullable=False),
        sa.Column("utilisateur_id", sa.UUID(), nullable=False),
        sa.Column("valeur_mesuree", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("is_conforme", sa.Boolean(), nullable=False),
        sa.Column("source", sa.Enum("MANUEL", "IOT", name="source_releve"), nullable=False),
        sa.Column("mesure_effectuee_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["equipement_id"],
            ["equipements.id"],
            name=op.f("fk_releves_temperature_equipement_id_equipements"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["etablissement_id"],
            ["etablissements.id"],
            name=op.f("fk_releves_temperature_etablissement_id_etablissements"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["utilisateur_id"],
            ["utilisateurs.id"],
            name=op.f("fk_releves_temperature_utilisateur_id_utilisateurs"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_releves_temperature")),
    )
    op.create_index(
        op.f("ix_releves_temperature_equipement_id"),
        "releves_temperature",
        ["equipement_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_releves_temperature_etablissement_id"),
        "releves_temperature",
        ["etablissement_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_releves_temperature_utilisateur_id"),
        "releves_temperature",
        ["utilisateur_id"],
        unique=False,
    )
    op.create_table(
        "actions_correctives",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("releve_id", sa.UUID(), nullable=False),
        sa.Column("utilisateur_id", sa.UUID(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("photo_s3_key", sa.String(length=1024), nullable=True),
        sa.Column("signee_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["releve_id"],
            ["releves_temperature.id"],
            name=op.f("fk_actions_correctives_releve_id_releves_temperature"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["utilisateur_id"],
            ["utilisateurs.id"],
            name=op.f("fk_actions_correctives_utilisateur_id_utilisateurs"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_actions_correctives")),
    )
    op.create_index(
        op.f("ix_actions_correctives_releve_id"), "actions_correctives", ["releve_id"], unique=True
    )
    op.create_index(
        op.f("ix_actions_correctives_utilisateur_id"),
        "actions_correctives",
        ["utilisateur_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_actions_correctives_utilisateur_id"), table_name="actions_correctives")
    op.drop_index(op.f("ix_actions_correctives_releve_id"), table_name="actions_correctives")
    op.drop_table("actions_correctives")
    op.drop_index(op.f("ix_releves_temperature_utilisateur_id"), table_name="releves_temperature")
    op.drop_index(op.f("ix_releves_temperature_etablissement_id"), table_name="releves_temperature")
    op.drop_index(op.f("ix_releves_temperature_equipement_id"), table_name="releves_temperature")
    op.drop_table("releves_temperature")
    op.drop_index(op.f("ix_pointages_utilisateur_id"), table_name="pointages")
    op.drop_index(op.f("ix_pointages_etablissement_id"), table_name="pointages")
    op.drop_table("pointages")
    op.drop_index(op.f("ix_equipements_etablissement_id"), table_name="equipements")
    op.drop_table("equipements")
    op.drop_table("affectations_site")
    op.drop_index(op.f("ix_etablissements_organisation_id"), table_name="etablissements")
    op.drop_table("etablissements")
    op.drop_index(op.f("ix_abonnements_organisation_id"), table_name="abonnements")
    op.drop_table("abonnements")
    op.drop_index(op.f("ix_utilisateurs_email"), table_name="utilisateurs")
    op.drop_table("utilisateurs")
    op.drop_table("roles")
    op.drop_table("organisations")
    # ### end Alembic commands ###
